"""add_ledger_and_double_entry_tables

Revision ID: 0aa3cead7939
Revises: afdbc8d657f6
Create Date: 2026-05-31 10:35:51.532675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa3cead7939'
down_revision: Union[str, Sequence[str], None] = 'afdbc8d657f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_chart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='account_category_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_chart_company_code', 'accounts_chart', ['company_id', 'code'], unique=False)
    op.create_index('ix_accounts_chart_company_id', 'accounts_chart', ['company_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('source_doc_type', sa.String(length=64), nullable=True),
    sa.Column('source_doc_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_entries_company_id', 'journal_entries', ['company_id'], unique=False)
    op.create_index('ix_journal_entries_operation_date', 'journal_entries', ['company_id', 'operation_date'], unique=False)
    op.create_table('ledger_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_chart_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (debit = 0 AND credit > 0)', name='check_debit_credit_xor'),
    sa.ForeignKeyConstraint(['account_chart_id'], ['accounts_chart.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_lines_account_id', 'ledger_lines', ['account_chart_id'], unique=False)
    op.create_index('ix_ledger_lines_journal_id', 'ledger_lines', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_lines_journal_id', table_name='ledger_lines')
    op.drop_index('ix_ledger_lines_account_id', table_name='ledger_lines')
    op.drop_table('ledger_lines')
    op.drop_index('ix_journal_entries_operation_date', table_name='journal_entries')
    op.drop_index('ix_journal_entries_company_id', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_accounts_chart_company_id', table_name='accounts_chart')
    op.drop_index('ix_accounts_chart_company_code', table_name='accounts_chart')
    op.drop_table('accounts_chart')
    # ### end Alembic commands ###
