"""add_currency_rates_table

Revision ID: 25b2b35ff251
Revises: 0e773e6e466c
Create Date: 2026-06-01 00:05:28.785093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b2b35ff251'
down_revision: Union[str, Sequence[str], None] = '0e773e6e466c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'rate_date', name='ux_currency_code_date')
    )
    op.create_index('ix_currency_rates_code', 'currency_rates', ['currency_code'], unique=False)
    op.create_index('ix_currency_rates_date', 'currency_rates', ['rate_date'], unique=False)
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index('ix_currency_rates_date', table_name='currency_rates')
    op.drop_index('ix_currency_rates_code', table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
