"""add_assets_and_loans_with_schedules

Revision ID: 30819c83c7c8
Revises: 3f121d7196c9
Create Date: 2026-05-30 01:29:22.202389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30819c83c7c8'
down_revision: Union[str, Sequence[str], None] = '3f121d7196c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('amortization_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_amortization', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_company_active', 'assets', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_assets_company_id', 'assets', ['company_id'], unique=False)
    op.create_index('ix_assets_purchase_date', 'assets', ['company_id', 'purchase_date'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('loan_type', sa.Enum('annuity', 'differentiated', name='loan_type_enum'), nullable=False),
    sa.Column('remaining_principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_company_active', 'loans', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_loans_company_id', 'loans', ['company_id'], unique=False)
    op.create_index('ix_loans_counterparty', 'loans', ['counterparty_id'], unique=False)
    op.create_table('loan_payment_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_schedule_date', 'loan_payment_schedule', ['loan_id', 'payment_date'], unique=False)
    op.create_index('ix_loan_schedule_loan_id', 'loan_payment_schedule', ['loan_id'], unique=False)
    op.create_index('ix_loan_schedule_unpaid', 'loan_payment_schedule', ['loan_id', 'is_paid'], unique=False)
    op.add_column('transactions', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('loan_id', sa.UUID(), nullable=True))
    op.create_index('ix_transactions_asset_id', 'transactions', ['asset_id'], unique=False)
    op.create_index('ix_transactions_loan_id', 'transactions', ['loan_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'loans', ['loan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'assets', ['asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_loan_id', table_name='transactions')
    op.drop_index('ix_transactions_asset_id', table_name='transactions')
    op.drop_column('transactions', 'loan_id')
    op.drop_column('transactions', 'asset_id')
    op.drop_index('ix_loan_schedule_unpaid', table_name='loan_payment_schedule')
    op.drop_index('ix_loan_schedule_loan_id', table_name='loan_payment_schedule')
    op.drop_index('ix_loan_schedule_date', table_name='loan_payment_schedule')
    op.drop_table('loan_payment_schedule')
    op.drop_index('ix_loans_counterparty', table_name='loans')
    op.drop_index('ix_loans_company_id', table_name='loans')
    op.drop_index('ix_loans_company_active', table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_assets_purchase_date', table_name='assets')
    op.drop_index('ix_assets_company_id', table_name='assets')
    op.drop_index('ix_assets_company_active', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
