"""add_projects_budgets_and_requests

Revision ID: 3f121d7196c9
Revises: a5c64b8ddab3
Create Date: 2026-05-29 22:14:43.643075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f121d7196c9'
down_revision: Union[str, Sequence[str], None] = 'a5c64b8ddab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_company_active', 'projects', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('plan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'category_id', 'project_id', 'year', 'month', name='uq_budget_category_project_month')
    )
    op.create_index('ix_budgets_category_id', 'budgets', ['category_id'], unique=False)
    op.create_index('ix_budgets_company_id', 'budgets', ['company_id'], unique=False)
    op.create_index('ix_budgets_company_year_month', 'budgets', ['company_id', 'year', 'month'], unique=False)
    op.create_index('ix_budgets_project_id', 'budgets', ['project_id'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('applicant_user_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paid', name='payment_request_status_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('paid_transaction_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_requests_applicant', 'payment_requests', ['applicant_user_id'], unique=False)
    op.create_index('ix_payment_requests_company_id', 'payment_requests', ['company_id'], unique=False)
    op.create_index('ix_payment_requests_company_status', 'payment_requests', ['company_id', 'status'], unique=False)
    op.create_index('ix_payment_requests_planned_date', 'payment_requests', ['company_id', 'planned_date'], unique=False)
    op.create_index('ix_payment_requests_project_id', 'payment_requests', ['project_id'], unique=False)
    op.add_column('invoices', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index('ix_invoices_project_id', 'invoices', ['project_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('project_id', sa.UUID(), nullable=True))
    # ix_transactions_transfer_id уже существует в БД (создан в sprint5_core_expansion)
    op.create_index('ix_transactions_project_id', 'transactions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_transactions_project_id', table_name='transactions')
    # ix_transactions_transfer_id намеренно не воссоздаётся здесь — он принадлежит sprint5
    op.drop_column('transactions', 'project_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index('ix_invoices_project_id', table_name='invoices')
    op.drop_column('invoices', 'project_id')
    op.drop_index('ix_payment_requests_project_id', table_name='payment_requests')
    op.drop_index('ix_payment_requests_planned_date', table_name='payment_requests')
    op.drop_index('ix_payment_requests_company_status', table_name='payment_requests')
    op.drop_index('ix_payment_requests_company_id', table_name='payment_requests')
    op.drop_index('ix_payment_requests_applicant', table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index('ix_budgets_project_id', table_name='budgets')
    op.drop_index('ix_budgets_company_year_month', table_name='budgets')
    op.drop_index('ix_budgets_company_id', table_name='budgets')
    op.drop_index('ix_budgets_category_id', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_projects_company_id', table_name='projects')
    op.drop_index('ix_projects_company_active', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
