"""add_accrual_documents_and_transaction_links

Revision ID: 68ee968daa4d
Revises: ee1b3e0e3d0f
Create Date: 2026-05-30 08:57:14.747558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ee968daa4d'
down_revision: Union[str, Sequence[str], None] = 'ee1b3e0e3d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accrual_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('doc_number', sa.String(length=128), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('doc_type', sa.Enum('revenue', 'expense', name='accrual_document_type_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'partially_paid', 'paid', 'overpaid', name='accrual_status_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accrual_docs_company_date', 'accrual_documents', ['company_id', 'doc_date'], unique=False)
    op.create_index('ix_accrual_docs_company_id', 'accrual_documents', ['company_id'], unique=False)
    op.create_index('ix_accrual_docs_company_status', 'accrual_documents', ['company_id', 'payment_status'], unique=False)
    op.create_index('ix_accrual_docs_company_type', 'accrual_documents', ['company_id', 'doc_type'], unique=False)
    op.create_index('ix_accrual_docs_counterparty_id', 'accrual_documents', ['counterparty_id'], unique=False)
    op.create_index('ix_accrual_docs_project_id', 'accrual_documents', ['project_id'], unique=False)
    op.create_table('transaction_accrual_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('accrual_document_id', sa.UUID(), nullable=False),
    sa.Column('linked_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('linked_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accrual_document_id'], ['accrual_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'accrual_document_id', name='uq_txn_accrual_link')
    )
    op.create_index('ix_txn_accrual_links_accrual_document_id', 'transaction_accrual_links', ['accrual_document_id'], unique=False)
    op.create_index('ix_txn_accrual_links_transaction_id', 'transaction_accrual_links', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txn_accrual_links_transaction_id', table_name='transaction_accrual_links')
    op.drop_index('ix_txn_accrual_links_accrual_document_id', table_name='transaction_accrual_links')
    op.drop_table('transaction_accrual_links')
    op.drop_index('ix_accrual_docs_project_id', table_name='accrual_documents')
    op.drop_index('ix_accrual_docs_counterparty_id', table_name='accrual_documents')
    op.drop_index('ix_accrual_docs_company_type', table_name='accrual_documents')
    op.drop_index('ix_accrual_docs_company_status', table_name='accrual_documents')
    op.drop_index('ix_accrual_docs_company_id', table_name='accrual_documents')
    op.drop_index('ix_accrual_docs_company_date', table_name='accrual_documents')
    op.drop_table('accrual_documents')
    # ### end Alembic commands ###
