"""add_billing_subscriptions

Revision ID: 7ea5b5fdc2ff
Revises: 2f2deb0f738a
Create Date: 2026-06-01 00:36:10.174895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ea5b5fdc2ff'
down_revision: Union[str, Sequence[str], None] = '2f2deb0f738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_name', sa.String(length=32), nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=128), nullable=True))
    op.add_column('subscriptions', sa.Column('yoomoney_payment_id', sa.String(length=128), nullable=True))
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'PAUSED', 'EXPIRED', name='subscription_status_enum'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(length=16),
               type_=postgresql.ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'PAUSED', 'EXPIRED', name='subscription_status_enum'),
               existing_nullable=False)
    op.drop_column('subscriptions', 'yoomoney_payment_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'plan_name')
    # ### end Alembic commands ###
