"""add_loans_and_schedules_tables

Revision ID: 8fa7b4bddc3a
Revises: d797f7279967
Create Date: 2026-05-31 18:21:39.636980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa7b4bddc3a'
down_revision: Union[str, Sequence[str], None] = 'd797f7279967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('counterpart_id', sa.UUID(), nullable=True),
    sa.Column('contract_number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'LOAN_ISSUED', 'LOAN_RECEIVED', name='loantype'), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['counterpart_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_contracts_company', 'loan_contracts', ['company_id'], unique=False)
    op.create_table('loan_payment_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_contract_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loan_contract_id'], ['loan_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loan_schedules_date', 'loan_payment_schedules', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_schedules_date', table_name='loan_payment_schedules')
    op.drop_table('loan_payment_schedules')
    op.drop_index('ix_loan_contracts_company', table_name='loan_contracts')
    op.drop_table('loan_contracts')
    # ### end Alembic commands ###
