"""sprint5_core_expansion

Revision ID: a5c64b8ddab3
Revises: e253f1af6ccd
Create Date: 2026-05-29 21:17:37.008331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5c64b8ddab3'
down_revision: Union[str, Sequence[str], None] = 'e253f1af6ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем роль MANAGER в PostgreSQL enum (IF NOT EXISTS — PostgreSQL 12+)
    op.execute(sa.text("ALTER TYPE user_role_enum ADD VALUE IF NOT EXISTS 'MANAGER'"))

    # Индекс для transfer_id (добавляется вместе с колонкой ниже)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('counterparties', 'is_customer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('counterparties', 'is_supplier',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('counterparties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('counterparties', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', 'CNY', 'KZT', name='currency_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('pending', 'partially_paid', 'paid', 'cancelled', name='invoice_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('transactions', sa.Column('transfer_id', sa.UUID(), nullable=True))
    op.create_index('ix_transactions_transfer_id', 'transactions', ['transfer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transfer_id', table_name='transactions')
    op.drop_column('transactions', 'transfer_id')
    # Note: PostgreSQL не поддерживает DROP VALUE из enum — MANAGER остаётся в типе
    op.alter_column('invoices', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('pending', 'partially_paid', 'paid', 'cancelled', name='invoice_status_enum'),
               server_default=sa.text("'pending'::invoice_status_enum"),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', 'CNY', 'KZT', name='currency_enum'),
               server_default=sa.text("'RUB'::currency_enum"),
               existing_nullable=False)
    op.alter_column('counterparties', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('counterparties', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('counterparties', 'is_supplier',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('counterparties', 'is_customer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
