"""add_inventory_and_stock_tables

Revision ID: afdbc8d657f6
Revises: b05a7a76abe8
Create Date: 2026-05-31 00:42:00.535588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdbc8d657f6'
down_revision: Union[str, Sequence[str], None] = 'b05a7a76abe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_items_company_id', 'stock_items', ['company_id'], unique=False)
    op.create_index('ix_stock_items_company_sku', 'stock_items', ['company_id', 'sku'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouses_company_id', 'warehouses', ['company_id'], unique=False)
    op.create_table('stock_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('incoming', 'outgoing', 'transfer', name='stock_operation_type_enum'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_ops_batch_id', 'stock_operations', ['batch_id'], unique=False)
    op.create_index('ix_stock_ops_company_id', 'stock_operations', ['company_id'], unique=False)
    op.create_index('ix_stock_ops_item_wh_date', 'stock_operations', ['stock_item_id', 'warehouse_id', 'operation_date'], unique=False)
    op.create_index('ix_stock_ops_operation_date', 'stock_operations', ['company_id', 'operation_date'], unique=False)
    op.create_index('ix_stock_ops_stock_item_id', 'stock_operations', ['stock_item_id'], unique=False)
    op.create_index('ix_stock_ops_warehouse_id', 'stock_operations', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_ops_warehouse_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_stock_item_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_operation_date', table_name='stock_operations')
    op.drop_index('ix_stock_ops_item_wh_date', table_name='stock_operations')
    op.drop_index('ix_stock_ops_company_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_batch_id', table_name='stock_operations')
    op.drop_table('stock_operations')
    op.drop_index('ix_warehouses_company_id', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('ix_stock_items_company_sku', table_name='stock_items')
    op.drop_index('ix_stock_items_company_id', table_name='stock_items')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
