"""add_bank_sync_logging_and_fields

Revision ID: b05a7a76abe8
Revises: efba1deb4dc7
Create Date: 2026-05-30 16:04:46.280849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05a7a76abe8'
down_revision: Union[str, Sequence[str], None] = 'efba1deb4dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_connection_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('transactions_fetched', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_sync_logs_company_id', 'bank_sync_logs', ['company_id'], unique=False)
    op.create_index('ix_bank_sync_logs_connection_id', 'bank_sync_logs', ['bank_connection_id'], unique=False)
    op.create_index('ix_bank_sync_logs_created_at', 'bank_sync_logs', ['bank_connection_id', 'created_at'], unique=False)
    op.create_index('ix_bank_sync_logs_status', 'bank_sync_logs', ['bank_connection_id', 'status'], unique=False)
    op.alter_column('accrual_documents', 'is_intra_group',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('bank_connections', sa.Column('api_token', sa.String(length=1024), nullable=True))
    op.add_column('bank_connections', sa.Column('account_number', sa.String(length=64), nullable=True))
    op.alter_column('transactions', 'is_intra_group',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'is_intra_group',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('bank_connections', 'account_number')
    op.drop_column('bank_connections', 'api_token')
    op.alter_column('accrual_documents', 'is_intra_group',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index('ix_bank_sync_logs_status', table_name='bank_sync_logs')
    op.drop_index('ix_bank_sync_logs_created_at', table_name='bank_sync_logs')
    op.drop_index('ix_bank_sync_logs_connection_id', table_name='bank_sync_logs')
    op.drop_index('ix_bank_sync_logs_company_id', table_name='bank_sync_logs')
    op.drop_table('bank_sync_logs')
    # ### end Alembic commands ###
