"""add_fixed_assets_tables

Revision ID: d797f7279967
Revises: fca33fa70465
Create Date: 2026-05-31 17:28:07.881188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd797f7279967'
down_revision: Union[str, Sequence[str], None] = 'fca33fa70465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inventory_number', sa.String(length=64), nullable=False),
    sa.Column('initial_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('lifespan_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECIATED', 'WRITTEN_OFF', name='fixedassetstatus'), nullable=False),
    sa.Column('account_chart_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_chart_id'], ['accounts_chart.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixed_assets_company_status', 'fixed_assets', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fixed_assets_company_status', table_name='fixed_assets')
    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
