"""add_bank_connections_for_directbank

Revision ID: ee1b3e0e3d0f
Revises: 30819c83c7c8
Create Date: 2026-05-30 01:57:32.651378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee1b3e0e3d0f'
down_revision: Union[str, Sequence[str], None] = '30819c83c7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'error', 'expired', 'disconnected', name='bank_connection_status_enum'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sync_from_date', sa.Date(), nullable=True),
    sa.Column('auto_classify', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_bank_connection_account')
    )
    op.create_index('ix_bank_connections_bank_name', 'bank_connections', ['company_id', 'bank_name'], unique=False)
    op.create_index('ix_bank_connections_company_id', 'bank_connections', ['company_id'], unique=False)
    op.create_index('ix_bank_connections_status', 'bank_connections', ['company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_connections_status', table_name='bank_connections')
    op.drop_index('ix_bank_connections_company_id', table_name='bank_connections')
    op.drop_index('ix_bank_connections_bank_name', table_name='bank_connections')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
