"""add_intra_group_links_and_vgo_flags

Revision ID: efba1deb4dc7
Revises: fdc24214d3bd
Create Date: 2026-05-30 15:39:23.168910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efba1deb4dc7'
down_revision: Union[str, Sequence[str], None] = 'fdc24214d3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intra_group_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_transaction_id', sa.UUID(), nullable=True),
    sa.Column('destination_transaction_id', sa.UUID(), nullable=True),
    sa.Column('source_accrual_id', sa.UUID(), nullable=True),
    sa.Column('destination_accrual_id', sa.UUID(), nullable=True),
    sa.Column('linked_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n              (source_transaction_id IS NOT NULL AND destination_transaction_id IS NOT NULL\n               AND source_accrual_id IS NULL AND destination_accrual_id IS NULL)\n              OR\n              (source_accrual_id IS NOT NULL AND destination_accrual_id IS NOT NULL\n               AND source_transaction_id IS NULL AND destination_transaction_id IS NULL)\n            )\n            ', name='ck_intra_group_either_txn_or_accrual'),
    sa.ForeignKeyConstraint(['destination_accrual_id'], ['accrual_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_accrual_id'], ['accrual_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intra_group_dest_accrual', 'intra_group_links', ['destination_accrual_id'], unique=False)
    op.create_index('ix_intra_group_dest_txn', 'intra_group_links', ['destination_transaction_id'], unique=False)
    op.create_index('ix_intra_group_source_accrual', 'intra_group_links', ['source_accrual_id'], unique=False)
    op.create_index('ix_intra_group_source_txn', 'intra_group_links', ['source_transaction_id'], unique=False)
    op.add_column('accrual_documents', sa.Column('is_intra_group', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('transactions', sa.Column('is_intra_group', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_intra_group')
    op.drop_column('accrual_documents', 'is_intra_group')
    op.drop_index('ix_intra_group_source_txn', table_name='intra_group_links')
    op.drop_index('ix_intra_group_source_accrual', table_name='intra_group_links')
    op.drop_index('ix_intra_group_dest_txn', table_name='intra_group_links')
    op.drop_index('ix_intra_group_dest_accrual', table_name='intra_group_links')
    op.drop_table('intra_group_links')
    # ### end Alembic commands ###
