"""add_auto_rules

Revision ID: f097cc44dfb7
Revises: 3e61d15cc460
Create Date: 2026-05-29 15:54:44.049197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f097cc44dfb7'
down_revision: Union[str, Sequence[str], None] = '3e61d15cc460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_to_match', sa.Enum('DESCRIPTION', 'COUNTERPARTY_INN', 'COUNTERPARTY_NAME', name='match_field_enum'), nullable=False),
    sa.Column('match_type', sa.Enum('CONTAINS', 'REGEX', 'EXACT', name='match_type_enum'), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('suggested_category_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auto_rules_company_active', 'auto_rules', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_auto_rules_company_id', 'auto_rules', ['company_id'], unique=False)
    op.create_index('ix_auto_rules_company_priority', 'auto_rules', ['company_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auto_rules_company_priority', table_name='auto_rules')
    op.drop_index('ix_auto_rules_company_id', table_name='auto_rules')
    op.drop_index('ix_auto_rules_company_active', table_name='auto_rules')
    op.drop_table('auto_rules')
    # ### end Alembic commands ###
