"""add_tax_regime_to_companies

Revision ID: fadbb5b0d8f9
Revises: 82908d2f38e1
Create Date: 2026-06-06 18:22:12.611913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fadbb5b0d8f9'
down_revision: Union[str, Sequence[str], None] = '82908d2f38e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_leaves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_items_company_id', 'stock_items', ['company_id'], unique=False)
    op.create_index('ix_stock_items_company_sku', 'stock_items', ['company_id', 'sku'], unique=False)
    op.create_table('stock_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('incoming', 'outgoing', 'transfer', name='stock_operation_type_enum'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_ops_batch_id', 'stock_operations', ['batch_id'], unique=False)
    op.create_index('ix_stock_ops_company_id', 'stock_operations', ['company_id'], unique=False)
    op.create_index('ix_stock_ops_item_wh_date', 'stock_operations', ['stock_item_id', 'warehouse_id', 'operation_date'], unique=False)
    op.create_index('ix_stock_ops_operation_date', 'stock_operations', ['company_id', 'operation_date'], unique=False)
    op.create_index('ix_stock_ops_stock_item_id', 'stock_operations', ['stock_item_id'], unique=False)
    op.create_index('ix_stock_ops_warehouse_id', 'stock_operations', ['warehouse_id'], unique=False)
    op.drop_table('crm_deals')
    op.drop_table('transaction_templates')
    op.drop_table('stock_levels')
    # Создаём тип enum явно перед использованием
    tax_regime_enum = sa.Enum('OSN', 'USN_INCOME', 'USN_PROFIT', 'PATENT', 'ENVD', 'ESHN', 'NPD', name='tax_regime_enum')
    tax_regime_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('companies', sa.Column('tax_regime', tax_regime_enum, nullable=True))
    op.execute("UPDATE companies SET tax_regime = 'USN_INCOME' WHERE tax_regime IS NULL")
    op.alter_column('companies', 'tax_regime', nullable=False)
    op.alter_column('payment_requests', 'transaction_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('warehouses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('warehouses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('warehouses', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('warehouses', 'location',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_index('ix_warehouses_company_id', 'warehouses', ['company_id'], unique=False)
    op.drop_constraint(op.f('warehouses_company_id_fkey'), 'warehouses', type_='foreignkey')
    op.create_foreign_key(None, 'warehouses', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_foreign_key(op.f('warehouses_company_id_fkey'), 'warehouses', 'companies', ['company_id'], ['id'])
    op.drop_index('ix_warehouses_company_id', table_name='warehouses')
    op.alter_column('warehouses', 'location',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('warehouses', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('warehouses', 'deleted_at')
    op.drop_column('warehouses', 'is_deleted')
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'created_at')
    op.alter_column('payment_requests', 'transaction_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'EXPENSE'::character varying"),
               existing_nullable=True)
    op.drop_column('companies', 'tax_regime')
    op.create_table('stock_levels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reserved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minimum_required', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('stock_levels_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_levels_pkey'))
    )
    op.create_table('transaction_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('transaction_templates_account_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('transaction_templates_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('transaction_templates_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_templates_pkey'))
    )
    op.create_table('crm_deals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('counterparty_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('counterparty_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('LEAD', 'CONTACT', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', name='deal_status_enum'), autoincrement=False, nullable=False),
    sa.Column('probability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_close_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('crm_deals_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('crm_deals_counterparty_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('crm_deals_pkey'))
    )
    op.drop_index('ix_stock_ops_warehouse_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_stock_item_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_operation_date', table_name='stock_operations')
    op.drop_index('ix_stock_ops_item_wh_date', table_name='stock_operations')
    op.drop_index('ix_stock_ops_company_id', table_name='stock_operations')
    op.drop_index('ix_stock_ops_batch_id', table_name='stock_operations')
    op.drop_table('stock_operations')
    op.drop_index('ix_stock_items_company_sku', table_name='stock_items')
    op.drop_index('ix_stock_items_company_id', table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_table('employee_leaves')
    # ### end Alembic commands ###
