"""add_tax_vat_records_table

Revision ID: fca33fa70465
Revises: 0aa3cead7939
Create Date: 2026-05-31 16:52:55.298358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca33fa70465'
down_revision: Union[str, Sequence[str], None] = '0aa3cead7939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_vat_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('vat_rate', sa.Enum('VAT_0', 'VAT_10', 'VAT_20', 'VAT_NONE', name='vatrate'), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vat_company_date', 'tax_vat_records', ['company_id', 'operation_date'], unique=False)
    op.create_index('ix_vat_doc', 'tax_vat_records', ['document_type', 'document_id'], unique=False)
    op.create_index('ix_vat_input_output', 'tax_vat_records', ['company_id', 'is_input'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vat_input_output', table_name='tax_vat_records')
    op.drop_index('ix_vat_doc', table_name='tax_vat_records')
    op.drop_index('ix_vat_company_date', table_name='tax_vat_records')
    op.drop_table('tax_vat_records')
    # ### end Alembic commands ###
