"""add_vat_fields_and_payroll_tables

Revision ID: fdc24214d3bd
Revises: 68ee968daa4d
Create Date: 2026-05-30 13:35:41.441872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc24214d3bd'
down_revision: Union[str, Sequence[str], None] = '68ee968daa4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_company_active', 'employees', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_employees_company_id', 'employees', ['company_id'], unique=False)
    op.create_table('payroll_calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('month_date', sa.Date(), nullable=False),
    sa.Column('accrued_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('accrued_bonus', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_accrued', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'accrued', 'paid', name='payroll_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_id', 'month_date', name='uq_payroll_company_employee_month')
    )
    op.create_index('ix_payroll_company_id', 'payroll_calculations', ['company_id'], unique=False)
    op.create_index('ix_payroll_company_month', 'payroll_calculations', ['company_id', 'month_date'], unique=False)
    op.create_index('ix_payroll_company_status', 'payroll_calculations', ['company_id', 'status'], unique=False)
    op.create_index('ix_payroll_employee_id', 'payroll_calculations', ['employee_id'], unique=False)
    op.add_column('accrual_documents', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('accrual_documents', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'vat_amount')
    op.drop_column('transactions', 'vat_rate')
    op.drop_column('accrual_documents', 'vat_amount')
    op.drop_column('accrual_documents', 'vat_rate')
    op.drop_index('ix_payroll_employee_id', table_name='payroll_calculations')
    op.drop_index('ix_payroll_company_status', table_name='payroll_calculations')
    op.drop_index('ix_payroll_company_month', table_name='payroll_calculations')
    op.drop_index('ix_payroll_company_id', table_name='payroll_calculations')
    op.drop_table('payroll_calculations')
    op.drop_index('ix_employees_company_id', table_name='employees')
    op.drop_index('ix_employees_company_active', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
